USE [master]
GO

/****** Object:  Database [loja]    Script Date: 14/02/2026 23:12:32 ******/
CREATE DATABASE [loja]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'loja', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\loja.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'loja_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\loja_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [loja].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [loja] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [loja] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [loja] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [loja] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [loja] SET ARITHABORT OFF 
GO

ALTER DATABASE [loja] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [loja] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [loja] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [loja] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [loja] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [loja] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [loja] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [loja] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [loja] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [loja] SET  ENABLE_BROKER 
GO

ALTER DATABASE [loja] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [loja] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [loja] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [loja] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [loja] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [loja] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [loja] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [loja] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [loja] SET  MULTI_USER 
GO

ALTER DATABASE [loja] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [loja] SET DB_CHAINING OFF 
GO

ALTER DATABASE [loja] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [loja] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [loja] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [loja] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [loja] SET QUERY_STORE = OFF
GO

ALTER DATABASE [loja] SET  READ_WRITE 
GO

